version: "3"

services: 
    front:
        container_name: front-end
        image: nginx:1.14.2-alpine
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./03_GL_Triangles:/usr/share/nginx/html:ro